### ISSUE TITLE
Add Airtable database setup?

### ISSUE THREAD

**Issue by lasseklein** [snipcart/gridsome-graphql-snipcart#1]
Thank you for this great tutorial. I have followed your instructions, but I get an error message that I believe might have to do with my Airtable setup. It would really help if you could share a read-only and cloneable version of your Airtable base or maybe list the tables that are not visible in the screenshot

Any help greatly appreciated!

The error I'm getting is:
```
ERROR in ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query (./node_modules/babel-loader/lib??ref--13-0!./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query)
Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "content" on type "Product".

GraphQL request (91:9)
90:         price,
91:         content,
            ^
92:         picture {

    at Object.module.exports (/Users/lasse.klein/Sites/snipcart-gridsome-airtable-demo/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:28:21)

```

**Comment by JeanSebTr** [comment]
Hey @lasseklein !

We started with [the product catalogue template](https://airtable.com/templates/featured/expZvMLT9L6c4yeBX/product-catalog).

**Comment by JeanSebTr** [comment]
It does indeed looks like the auto-generated graphql schemas doesn't match ours.

Best way to investigate what's returned by your airtable base would be to add a breakpoint or logging here: https://github.com/snipcart/gridsome-graphql-snipcart/blob/master/src/sources/products/index.js#L20

**Comment by lasseklein** [comment]
Thank you for pointing me to that Airtable base. I must have missed it.

Using that base instead of my own mockup got me past the "content"-error, but now I'm stranded at the next one "picture". I'm afraid I'm not a developer, and I don't yet have a good setup for debugging this. I can't find a configuration for npx, gridsome or vue in IntelliJ.

**Comment by lasseklein** [comment]
I didn't mean for this to become a support request. I guess my main contribution here is to suggest adding a link to the Airtable base to the tutorial.

I also suggest to investigate whether this compiles out of the box, as it doesn't for me after following the instructions. But if it works for others, then I must have missed something.

I changed to a capital P in Picture above, and now it compiles , but it gives a ton of error messages. I'll try from scratch again and let you know if it works out better.

Anyway: Thank you again for this great writeup. I have had great success prototyping with Airtable as a database, but this is a much better way of doing it, and It will be very useful for me to get it running.

**Comment by JeanSebTr** [comment]
Thanks @lasseklein !

That's great feedback. For now, I've updated the tutorial with the base's link.

I'll take some time later to update the demo's sources and tutorial steps to match new version of gridsome of Airtable's changes :)
