### ISSUE TITLE
Localhost:8080 Images not displayed based on "Gridsome Develop" of Github code 

### ISSUE THREAD

**Issue by critiquecom** [snipcart/gridsome-graphql-snipcart#3]
Hi  
Running Gridsome  version 0.7.10, Node V12.13, npm V6.12.0

Trying to diagnose why images are not being displayed  running localhost:8080. 
Graphql explorer shows Airtable data and image/picture URL present.
Running VS code debug  shows lines in extracted from 
Components/ProductPreview.vue below are UNDEFINED.
 
image: this.product.picture.length ? {
                name: this.product.picture[0].filename,
                url: this.product.picture[0].thumbnails.large.url.src,*

I am not an experienced developer of Vue code so have no idea how to diagnose why images are not being displayed. I have tried different browsers.  Also Console.log just shows "undefined"
What have I done wrong? Just wondering if I have a nesting issue or my environment settings (config.js) needs review.

Any advice on what the next diagnostic steps I could take to narrow down the problem  would be really appreciated.  Chris 

------------------------------------ProductPreview.vue--------------------
<template>
    <article>
        <g-link :to="product.path">
            <figure v-if="image">
                <img :src="image.url" :alt=image.name />
            </figure>
            <h2>{{product.name}}</h2>
        </g-link>
        <p class="btn-line">
            <BuyButton :product="product" />
        <p>{{excerpt}}</p>
    </article>
</template>

<script>

import BuyButton from './BuyButton'

function makeExcerpt(str, len) {
    var words = str.substr(0, len).split(' ');
    return words.slice(0, words.length - 1).join(' ') + '…';
}

	  
export default {
    name: 'ProductPreview',
    props: ['product'],
    components: {
        BuyButton,
    },
    data() {
		return {
            excerpt: makeExcerpt(this.product.description, 125),
            **image: this.product.picture.length ? {
                name: this.product.picture[0].filename,
                url: this.product.picture[0].thumbnails.large.url.src,**
				
            } : null,
		  };
		
	  }
    };
</script>

**Comment by JeanSebTr** [comment]
hi @critiquecom !

A few things to look out for:
- the data & naming of fields in AirTable: there has been a change in the sample data at least once since we made the tutorial
- how Gridsome maps fields to GraphQl types. I'm not sure that's the cause, but that might have changed slightly between versions

Best way to know is like you did, to check the Graphql explorer and validate that `product.picture[0].filename` and `product.picture[0].thumbnails.large.url.src` exist.

**Comment by critiquecom** [comment]
Hi JeanSebTr!
Thanks for taking the time to reply and the hint. 

- Yes I have spent many hours looking at the airtable fields, plus renaming them to match. I have tested using the earlier version of Gridsome with the same result. No images displayed. The frustration is there are no compile errors. I am clearly missing something obvious! The only common factor here is airtable.

- I have attached the screen capture of the explorer graphql population. This shows the URL field is populated that I am guessing is correct.

- Being new to Gridsome I have assumed that Gridsome loads and stores the images to the Graphql data layer at compile time (under Develop command) ) and then provides  a map name to this image (ie., not the actual URL) as you said at your second bullet. If this assumption is correct I am puzzled where the images are stored and how this mapping occurs.

- As you can guess I really don't know where to look next. One thought I had is have I got the correct field type defined in Airtable?  Any additional thoughts welcome .Regards Chris

![image](https://user-images.githubusercontent.com/40445734/74510927-a9f83d80-4f69-11ea-9637-fe343bf69dcf.png)



![airtableGraphExplore](https://user-images.githubusercontent.com/40445734/74510842-76b5ae80-4f69-11ea-9fc9-e834ef210903.png)

**Comment by JeanSebTr** [comment]
There appears to be no `.src` in your data. Only
`product.picture[0].thumbnails.large.url`

Le ven. 14 févr. 2020 02 h 37, critiquecom <notifications@github.com> a
écrit :

**Comment by critiquecom** [comment]
Hi JeanSebTr!
Thanks for taking the time to reply and the hint. 

- Yes I have spent many hours looking at the airtable fields, plus renaming them to match. I have tested using the earlier version of Gridsome with the same result. No images displayed. The frustration is there are no compile errors. I am clearly missing something obvious! The only common factor here is airtable.

- I have attached the screen capture of the explorer graphql population. This shows the URL field is populated that I am guessing is correct.

- Being new to Gridsome I have assumed that Gridsome loads and stores the images to the Graphql data layer at compile time (under Develop command) ) and then provides  a map name to this image (ie., not the actual URL) as you said at your second bullet. If this assumption is correct I am puzzled where the images are stored and how this mapping occurs.

- As you can guess I really don't know where to look next. One thought I had is have I got the correct field type defined in Airtable?  Any additional thoughts welcome .Regards Chris

![image](https://user-images.githubusercontent.com/40445734/74510927-a9f83d80-4f69-11ea-9637-fe343bf69dcf.png)



![airtableGraphExplore](https://user-images.githubusercontent.com/40445734/74510842-76b5ae80-4f69-11ea-9fc9-e834ef210903.png)

**Comment by critiquecom** [comment]
Hi JeanSebTr!
Thank you! The presence of the additional  ".src"  in the demo code was the reason for the "undefined"  expression and lack of images. I simply deleted all  instances of the ".src" from the supplied demo code, the issue disappeared and viola the images appeared.  Hopefully this info will help others who have the same issue when running the demo code. My lack of experience as a developer certainly contributed to me thinking the reason was more complex than it was!
Thanks again!  
Since I am relatively new to GitHub not sure how to close the issue. Regards Chris

**Comment by JeanSebTr** [comment]
Glad that helped fix the issue!
